### ISSUE TITLE
Node function overrides Node application

### ISSUE THREAD

**Issue by ericwgreene** [aaronpowell/ps-nvmw#85] opened 2019-12-03 20:19 UTC
I am running Powershell Core 6.2.3 on macOS Catalina. After I install Powershell Core (fresh install) and the ps-nvm module, I can install a Node version, set the Node version, and run the "npm" and "npx" commands. But I cannot run the "node" command because it is blocked by a function named "Node". The module PSDesiredStateConfiguration seems to be installed when I install ps-nvm. I checked my system to ensure PSDesiredStateConfiguration was not installed before I installed ps-nvm and I did not explicitly installPSDesiredStateConfiguration.

```
PS /Users/ericwgreene> Get-Command node 

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Node                                               0.0        PSDesiredStateConfiguration

PS /Users/ericwgreene> Get-Command node -CommandType Application

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     node                                               0.0.0.0    /Users/ericwgreene/.local/share/powershell/Module…

```
Anyway, this "Node" function is blocking the very program I am trying to run. Yes, I can alias it to override the function but setting up an alias each time I change node versions seems to defeat the point of using a Node version manager.

Any thoughts on what I can do to work around this or any thoughts on what I am doing wrong? Otherwise, the Powershell module works great with Powershell Core and I would really like to use it.

**Comment by ericwgreene** [comment] 2019-12-05 03:09
Here was my solution to the problem described above. In my local profile file, I added the following code:

```
$defaultNodeVersion = 12

Function SetNodeVersion {
  $originalSetNodeVersion = (Get-Command Set-NodeVersion -Module nvm)
  &($originalSetNodeVersion) @args
  $node = (Get-Command -Name node -CommandType Application | Select-Object -Expand Source)
  Set-Alias -Name node -Value $node -Scope Global
}

New-Alias -Name Set-NodeVersion -Value SetNodeVersion

Set-NodeVersion $defaultNodeVersion
```
When the aliased `Set-NodeVersion` function is called, the original `Set-NodeVersion` from the nvm module is executed. Then using the `Get-Command` cmdlet with a `-Type` value of 'Application' the hidden "node" application can be located and then setup as an alias. Because the "node" application path will change when the original `Set-NodeVersion` function is invoked, the alias updates to the newly set Node.js version.

So this hack gets the job done, but an official fix to the nvm module would be better if you have a chance. Thanks!

**Comment by aaronpowell** [comment] 2019-12-09 05:06
I don't have access to a Mac so I'm not going to be much help in fixing it. If the problem is to do with clashes across multiple installed modules I can't think of a better solution than the hacky approach you have in place.

**Comment by bladeoflight16** [comment] 2020-02-12 17:54
@ericwgreene Your function can be simplified by prefixing the original `Set-NodeVersion` with the module name and just naming the function the same as the original:

```
Function Set-NodeVersion {
    nvm\Set-NodeVersion @args
    $node = (Get-Command -Name node -CommandType Application).Source
    Set-Alias -Name node -Value $node -Scope Global
}
```

The new function will take precedence over the module. (Normally, anyway. There's weirdness with name conflicts if you invoke `Import-Module` again. PowerShell handles name conflicts *very* poorly.)

I recommend giving your user profile script a `#Requires nvm` to ensure it's loaded when you start the shell and then include the function above in it. Then you won't have to invoke any of this manually.

**Comment by aaronpowell** [comment] 2020-05-25 03:48
I can't seem to replicate this on any of my testing and I can't find any trace of installing the DSC module.

I'm going to close this as there's a viable workaround if people hit it, but it's not something I think needs to be in the core.

**Closed as completed by aaronpowell** 2020-05-25 03:48 UTC
